# Generated by Django 5.0.3 on 2024-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('complement_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('date_embauche', models.DateField()),
                ('login', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
    ]
