# Generated by Django 5.0.3 on 2024-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVisiteurs', '0004_rapport_createur_alter_utilisateur_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('specialisteComplimentaire', models.CharField(blank=True, max_length=255, null=True)),
                ('departement', models.CharField(max_length=100)),
            ],
        ),
    ]
