# Generated by Django 5.0.3 on 2024-04-15 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVisiteurs', '0006_medicament_rename_composition_rapport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionVisiteurs.medecin'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='medicament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionVisiteurs.medicament'),
        ),
    ]
