# Generated by Django 5.0.3 on 2024-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVisiteurs', '0007_rapport_medecin_rapport_medicament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='quantite',
        ),
        migrations.AddField(
            model_name='rapport',
            name='quantite',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='effets',
            field=models.CharField(max_length=100),
        ),
    ]
